const WORDS = {
  common: [
    "aku", "kamu", "dia", "kami", "kita", "mereka", "ini", "itu",
    "yang", "dan", "di", "ke", "dari", "dengan", "untuk", "pada",
    "adalah", "akan", "juga", "sudah", "tidak", "bisa", "ada", "hal",
    "orang", "waktu", "tahun", "hari", "bulan", "minggu", "jam",
    "makan", "minum", "tidur", "jalan", "lari", "duduk", "berdiri",
    "besar", "kecil", "panjang", "pendek", "tinggi", "rendah",
    "baik", "buruk", "cantik", "jelek", "baru", "lama", "muda", "tua",
    "air", "api", "tanah", "angin", "langit", "matahari", "bulan",
    "sayur", "buah", "nasi", "roti", "ikan", "ayam", "daging",
    "rumah", "jalan", "kota", "desa", "negara", "dunia",
    "buku", "pensil", "meja", "kursi", "pintu", "jendela",
    "baca", "tulis", "hitung", "bicara", "dengar", "lihat",
    "senang", "sedih", "marah", "takut", "heran", "suka",
    "hari", "pagi", "siang", "sore", "malam", "subuh",
    "satu", "dua", "tiga", "empat", "lima", "enam", "tujuh",
    "delapan", "sembilan", "sepuluh", "seratus", "seribu",
    "hitam", "putih", "merah", "biru", "hijau", "kuning", "coklat",
    "panas", "dingin", "hangat", "sejuk",
    "jauh", "dekat", "luas", "sempit", "datar", "tinggi",
    "semua", "banyak", "sedikit", "setiap", "beberapa",
    "dalam", "luar", "atas", "bawah", "kiri", "kanan", "depan", "belakang",
    "belajar", "mengajar", "bekerja", "bermain", "berlari", "berjalan",
    "masuk", "keluar", "naik", "turun", "buka", "tutup",
    "beri", "ambil", "pegang", "lepas", "kirim", "terima",
    "mulai", "selesai", "lanjut", "henti", "ulang",
    "cinta", "kasih", "sayang", "hangat", "damai",
    "mudah", "susah", "gampang", "sulit", "sederhana",
    "benar", "salah", "pasti", "mungkin", "tentu",
    "sangat", "lebih", "paling", "agak", "cukup",
    "sekali", "selalu", "kadang", "jarang", "pernah",
    "sekarang", "nanti", "tadi", "kemarin", "besok",
    "sini", "sana", "mana", "kemana", "darimana",
    "apa", "siapa", "kenapa", "bagaimana", "dimana",
    "kapan", "berapa", "mana", "ini", "itu",
    "mau", "harus", "perlu", "boleh", "sudi",
    "hidup", "mati", "lahir", "tumbuh", "berkembang",
    "datang", "pergi", "tinggal", "pulang", "singgah",
    "teman", "keluarga", "saudara", "tetangga", "guru",
    "kantor", "sekolah", "pasar", "toko", "rumah sakit",
    "sehat", "sakit", "kuat", "lemah", "capek",
    "senja", "fajar", "awan", "hujan", "embun",
    "cantik", "indah", "luar biasa", "hebat", "bagus",
    "tegas", "jujur", "sabar", "rajin", "pandai",
    "melon", "semangka", "jeruk", "mangga", "pisang",
    "kopi", "teh", "susu", "jus", "es",
    "pisau", "garpu", "sendok", "piring", "gelas",
    "baju", "celana", "topi", "sepatu", "kaos",
    "field", "computer", "keyboard", "phone", "screen",
    "internet", "website", "aplikasi", "program", "data",
    "kucing", "anjing", "burung", "sapi", "kuda", "ular", "bebek",
    "angsa", "tikus", "katak", "gajah", "singa", "monyet", "harimau",
    "kelinci", "mata", "mulut", "kaki", "dada", "lutut", "rambut",
    "hidung", "kepala", "perut", "telinga", "punggung",
    "gunung", "danau", "pantai", "sungai", "pohon", "hutan",
    "batu", "pasir", "lembah", "rawa",
    "mie", "telur", "keju", "gula", "garam", "mentega", "kacang",
    "lampu", "kunci", "dompet", "bantal", "selimut", "kamera", "jam",
    "kaca", "cermin", "sisir", "handuk",
    "masak", "cuci", "sapu", "nyanyi", "lompat", "lempar", "tangkap",
    "rebus", "goreng", "tarik", "dorong", "angkat", "bawa", "cari",
    "cerah", "lembut", "halus", "kasar", "gelap", "terang", "basah",
    "kering", "bersih", "kotor", "sepeda", "mobil", "kapal",
    "kereta api", "mesin cuci", "tanda tangan", "jam tangan",
    "lemari es", "kamar mandi", "ruang tamu", "meja makan",
    "toko buku", "jalan raya", "tenaga kerja", "surat kabar",
    "bahan bakar", "kunci pas", "sekolah dasar", "sapu tangan",
    "alat tulis", "pohon kelapa", "bunga mawar", "barang bekas",
    "lampu jalan", "pintu masuk"
  ],

  medium: [
    "berlari", "melompat", "menari", "berenang", "memanjat",
    "membaca", "menulis", "menggambar", "memasak", "mencuci",
    "menyapu", "menghapus", "menjahit", "merajut", "menganyam",
    "membangun", "merobohkan", "memperbaiki", "mengganti", "memindahkan",
    "menanam", "memanen", "menyiram", "mencangkul", "memupuk",
    "berdagang", "membeli", "menjual", "menawar", "membayar",
    "menyanyi", "bermain musik", "menggambar", "berpuisi", "bercerita",
    "berkelahi", "bertengkar", "berdamai", "berpelukan", "bersalaman",
    "berterima kasih", "minta maaf", "meminta", "menolak", "mengiyakan",
    "menghitung", "menjumlahkan", "mengurangi", "membagi", "mengalikan",
    "mengukur", "menimbang", "membandingkan", "menilai", "mengevaluasi",
    "organisasi", "pemerintah", "masyarakat", "penduduk", "warga negara",
    "ekonomi", "politik", "budaya", "sosial", "teknologi",
    "pendidikan", "kesehatan", "lingkungan", "transportasi", "komunikasi",
    "penelitian", "pengembangan", "pelatihan", "pertemuan", "presentasi",
    "dokumentasi", "pelaporan", "perencanaan", "pengawasan", "pengendalian",
    "kreativitas", "produktivitas", "efisiensi", "efektivitas", "kualitas",
    "motivasi", "inspirasi", "determinasi", "dedikasi", "komitmen",
    "tanggung jawab", "kemandirian", "kerjasama", "komunikasi", "leadership",
    "strategi", "implementasi", "evaluasi", "analisis", "sintesis",
    "konstruksi", "arsitektur", "infrastruktur", "ekskavasi", "fundasi",
    "elektronik", "mekanik", "hidrolik", "pneumatik", "optik",
    "astronomi", "biologi", "kimia", "fisika", "matematika",
    "geografi", "sejarah", "sosiologi", "psikologi", "filosofi",
    "sastra", "seni", "musik", "teater", "sinema",
    "fotografi", "videografi", "animasi", "desain", "arsitektur",
    "pertanian", "perkebunan", "peternakan", "perikanan", "kehutanan",
    "pertambangan", "industri", "manufaktur", "perdagangan", "jasa",
    "pariwisata", "hospitality", "logistik", "supply chain", "retail",
    "startup", "enterpreneurship", "investasi", "asuransi", "perbankan",
    "cryptocurrency", "blockchain", "artificial intelligence", "machine learning",
    "cloud computing", "cybersecurity", "data science", "big data",
    "virtual reality", "augmented reality", "internet of things",
    "sustainability", "renewable energy", "carbon footprint", "biodiversity",
    "ekosistem", "konservasi", "deforestasi", "globalisasi", "modernisasi",
    "digitalisasi", "transformasi", "revolusi", "inovasi", "disrupsi",
    "membantu", "memahami", "mengerti", "menjawab", "bertanya",
    "bercerita", "mengambil", "menunggu", "bertemu", "mengantar",
    "menjemput", "berangkat", "kembali",
    "gedung", "jembatan", "stasiun", "bandara", "pesawat",
    "penumpang", "pelabuhan",
    "dokter", "perawat", "petani", "nelayan", "pedagang",
    "pelayan", "koki", "tukang", "satpam", "montir",
    "merebus", "menumis", "mengukus", "menggoreng", "memanggang",
    "bersepeda", "beristirahat",
    "menyelesaikan", "mengerjakan",
    "perlengkapan", "kesempatan", "peraturan", "kebersihan",
    "perjalanan", "pengalaman", "pemahaman", "kepercayaan",
    "keindahan", "perpustakaan"
  ],

  sentences: [
    "aku suka makan nasi goreng",
    "kami pergi ke sekolah setiap hari",
    "dia sedang membaca buku di perpustakaan",
    "hari ini cuaca sangat cerah",
    "ibuku memasak sayur asem untuk makan siang",
    "ayah sedang bekerja di kantor",
    "adikku bermain bola di halaman rumah",
    "guru itu mengajar dengan sangat sabar",
    "kami tinggal di kota yang indah",
    "anjing itu berlari di taman",
    "bunga itu mekar di taman belakang",
    "hujan turun dengan sangat deras",
    "aku bangun pagi pukul lima",
    "kami sarapan bersama keluarga",
    "dia berangkat kerja naik bus",
    "anak-anak bermain di sungai",
    "kucing itu tidur di atas sofa",
    "pohon itu sangat tinggi dan besar",
    "kami piknik di tepi danau",
    "udara di pegunungan sangat sejuk",
    "nasi goreng adalah makanan favoritku",
    "jakarta adalah ibu kota indonesia",
    "batik adalah warisan budaya indonesia",
    "garuda pancasila lambang negara kita",
    "bahasa indonesia menyatukan negeri ini",
    "tropical fruits are delicious",
    "the weather is very hot today",
    "i love reading books at night",
    "she goes to school every morning",
    "we play football in the afternoon",
    "masakan rumah makan itu sangat lezat",
    "sepeda baruku berwarna merah dan hijau",
    "mereka bekerja keras di bawah panas matahari",
    "aku membaca buku cerita sebelum tidur",
    "ibu menanam bunga mawar di halaman depan",
    "kucing itu suka bermain dengan bola kecil",
    "para petani panen padi di sawah pagi ini",
    "kita harus menjaga kebersihan lingkungan sekitar",
    "dia belajar matematika bersama teman sekelasnya",
    "nelayan itu berlayar jauh mencari ikan di laut",
    "pohon mangga di belakang rumah sudah berbuah lebat",
    "aku dan adik menonton film di ruang keluarga",
    "kereta api berangkat dari stasiun tepat waktu",
    "bandara baru itu melayani banyak penumpang setiap hari",
    "saat hujan turun kami berteduh di bawah pohon besar"
  ],

  hard: [
    "pneumonoultramicroscopicsilicovolcanoconiosis",
    "hipopotomonstrosesquippedaliophobia",
    "supercalifragilisticexpialidocious",
    "kesehatan", "kemerdekaan", "kemandirian",
    "pembangunan", "pengembangan", "perencanaan",
    "pertanggungjawaban", "penyelenggaraan",
    "pengusahaan", "pemanfaatan", "perlindungan",
    "pengawasan", "pengendalian", "penyuluhan",
    "pemberdayaan", "pemberitaan", "penyiaran",
    "peradaban", "perkembangan", "perubahan",
    "keberagaman", "keberlanjutan", "kesinambungan",
    "revolusioner", "eksklusif", "inklusif",
    "multidimensi", "multikultural", "pluralis",
    "fundamental", "komprehensif", "proporsional",
    "autentik", "adaptif", "reaktif", "proaktif",
    "otonomi", "birokrasi", "teknokrasi", "demokrasi",
    "aristokrasi", "meritokrasi", "oligarki",
    "hegemoni", "dominasi", "supremasi",
    "paradoks", "dialektika", "retorika",
    "algoritma", "kriptografi", "steganografi",
    "neuroscience", "bioinformatics", "nanotechnology",
    "quantum mechanics", "thermodynamics",
    "electromagnetism", "superconductivity",
    "photosynthesis", "mitochondria",
    "deoxyribonucleic", "chromosome",
    "philosophy", "metaphysics", "epistemology",
    "hermeneutics", "phenomenology",
    "existentialism", "nihilism", "utilitarianism",
    "kontemporer", "representatif", "substansial", "kuantitatif",
    "kualitatif", "partisipatif", "instrumental", "konvensional",
    "eksperimental", "observasional", "transformasional",
    "telekomunikasi", "konsekuensi", "elaborasi", "kolaboratif",
    "integratif", "inovatif", "eksploratif"
  ]
};

const SENTENCES_ID = [
  "aku suka makan nasi goreng dengan ayam",
  "hari ini sangat panas sekali di kota ini",
  "dia pergi ke pasar untuk membeli sayur",
  "kami tinggal di desa yang tenang dan damai",
  "guru itu mengajar bahasa indonesia dengan baik",
  "anak-anak bermain di taman setelah sekolah",
  "ibu memasak makanan kesukaan kami setiap hari",
  "ayah membaca koran sambil minum kopi pagi ini",
  "kucing kecil itu tidur di atas kasur yang empuk",
  "bunga mawar mekar indah di taman belakang rumah",
  "hujan turun sejak tadi pagi dan belum berhenti",
  "aku bangun pagi untuk berolahraga di taman",
  "kami semua makan malam bersama di meja makan",
  "dia naik sepeda ke sekolah setiap hari pagi",
  "burung itu terbang tinggi di langit yang biru",
  "air sungai mengalir jauh ke laut yang biru",
  "pohon kelapa tinggi berdiri di tepi pantai",
  "kami piknik bersama di bukit yang asri",
  "udara pegunungan sejuk dan menyegarkan tubuh",
  "nasi goreng adalah makanan khas indonesia yang terkenal",
  "jakarta adalah pusat pemerintahan negara indonesia",
  "batik indonesia diakui oleh dunia internasional",
  "garuda pancasila adalah simbol kejayaan bangsa",
  "bahasa indonesia menyatukan seluruh nusantara",
  "tokopedia dan bukalapak adalah marketplace indonesia",
  "nasi padang enak sekali apalagi dengan rendang",
  "wayang kulit adalah seni pertunjukan tradisional jawa",
  "borobudur adalah candi terbesar di dunia",
  "raja ampat surga bawah laut indonesia",
  "komodo adalah hewan langka yang hanya ada di indonesia",
  "kopi aceh terkenal enak di seluruh dunia",
  "tari pendet adalah tarian tradisional dari bali",
  "gunung bromo terletak di jawa timur yang indah",
  "danau toba adalah danau vulkanik terbesar di dunia",
  "bahasa jawa adalah salah satu bahasa daerah di indonesia",
  "wayang golek adalah boneka kayu dari jawa barat",
  "sate ayam adalah makanan favorit semua orang indonesia",
  "rupiah adalah mata uang resmi negara indonesia",
  "pancasila adalah dasar negara republik indonesia",
  "soekarno adalah proklamator kemerdekaan indonesia",
  "indonesia merdeka pada tanggal tujuh belas agustus",
    "saya pergi ke pasar membeli sayur dan buah segar",
    "kakak menjemput adik di sekolah setiap sore",
    "sinar matahari pagi terasa hangat di kulit",
    "mereka berhasil menyelesaikan tugas kelompok dengan cepat",
    "toko buku favoritku buka mulai jam delapan pagi",
    "ayah memperbaiki sepeda motornya di garasi",
    "cucu itu duduk manis mendengarkan cerita nenek",
    "petani itu membajak sawah dengan kerbau yang kuat",
    "pesawat terbang meninggalkan landasan menuju awan",
    "kita perlu minum air putih yang cukup setiap hari",
    "anak-anak menyiram tanaman di kebun belakang rumah",
    "mobil itu melaju cepat di jalan raya yang sepi",
    "kami merayakan hari kemerdekaan dengan upacara bendera",
    "obat itu diminum dua kali sehari setelah makan",
    "selimut tebal membuatku hangat saat malam dingin"
];

const WORD_LISTS = {
  easy: WORDS.common.filter(w => w.length <= 5),
  medium: WORDS.common.filter(w => w.length > 5).concat(WORDS.medium.filter(w => w.length <= 8)),
  hard: WORDS.medium.concat(WORDS.hard),
  mixed: [...new Set([...WORDS.common, ...WORDS.medium])]
};
